SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `CargaPos`;
DELETE FROM `Curso`;
DELETE FROM `Disciplina`;
DELETE FROM `DisciplinaGrade`;
DELETE FROM `Docente`;
DELETE FROM `DocentePerfil`;
DELETE FROM `Grade`;
DELETE FROM `Horario`;
DELETE FROM `Pedido`;
DELETE FROM `PedidoExterno`;
DELETE FROM `Perfil`;
DELETE FROM `Sala`;
DELETE FROM `Turma`;
DELETE FROM `TurmaExterna`
DELETE FROM `Usuario`;
DELETE FROM `Vaga`;
SET FOREIGN_KEY_CHECKS = 1;