SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `curso`;
DELETE FROM `disciplina`;
DELETE FROM `disciplinagrade`;
DELETE FROM `docente`;
DELETE FROM `docenteperfil`;
DELETE FROM `grade`;
DELETE FROM `horario`;
DELETE FROM `pedido`;
DELETE FROM `perfil`;
DELETE FROM `sala`;
DELETE FROM `turma`;
DELETE FROM `usuario`;
DELETE FROM `vaga`;
SET FOREIGN_KEY_CHECKS = 1;