// general
export const COMPONENT_LOADING = 'COMPONENT_LOADING'
export const COMPONENT_LOADED = 'COMPONENT_LOADED'

// store.js
export const HTTP_REQUEST_INCREMENT = 'HTTP_REQUEST_INCREMENT'
export const HTTP_REQUEST_DECREMENT = 'HTTP_REQUEST_DECREMENT'

// auth.js
export const AUTHENTICATE = 'AUTHENTICATE'
export const USER_FETCHED = 'USER_FETCHED'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

// perfil.js
export const PERFIL_FETCHED = 'PERFIL_FETCHED'
export const SOCKET_PERFIL_UPDATED = 'SOCKET_PERFIL_UPDATED'
export const SOCKET_PERFIL_CREATED = 'SOCKET_PERFIL_CREATED'
export const SOCKET_PERFIL_DELETED = 'SOCKET_PERFIL_DELETED'

//curso.js
export const CURSO_FETCHED = 'CURSO_FETCHED'
export const SOCKET_CURSO_UPDATED = 'SOCKET_CURSO_UPDATED'
export const SOCKET_CURSO_CREATED = 'SOCKET_CURSO_CREATED'
export const SOCKET_CURSO_DELETED = 'SOCKET_CURSO_DELETED'

//disciplina.js
export const DISCIPLINA_FETCHED = 'DISCIPLINA_FETCHED'
export const SOCKET_DISCIPLINA_UPDATED = 'SOCKET_DISCIPLINA_UPDATED'
export const SOCKET_DISCIPLINA_CREATED = 'SOCKET_DISCIPLINA_CREATED'
export const SOCKET_DISCIPLINA_DELETED = 'SOCKET_DISCIPLINA_DELETED'
